export const bsHeadings = [
  "Share Capital",
  "Reserves & Surplus",
  "Long-term borrowings",
  "Money Received Against Share Warrants",
  "Share Application Money Pending Allotment",
  "Other long-term Liabilities",
  "Long-term Provisions",
  "Short-term borrowings",
  "Deferred Tax Liabilities",
  "total outstanding dues of MSME; and",
  "total outstanding dues of creditors other than MSME",
  "Other current liabilities",
  "Short-term Provisions",
  "Tangible Assets",
  "Intangible Assets",
  "Capital work-in progress",
  "Intangible Assets Under Development",
  "Non-Current Investments",
  "Long-term Loans & Advances",
  "Short-term Loans & Advances",
  "Other non-current Assets",
  "Current Investments",
  "Inventories",
  "Trade Receivables",
  "Cash & Cash Equivalents",
  "Other Current Assets",
  "Deferred Tax Assets",
];
