// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

interface PlanningContext {
  readSection: (companyName: string, sectionKey: string) => Promise<any>;
  saveSection: (
    companyName: string,
    sectionKey: string,
    content: unknown,
  ) => Promise<{ ok: boolean }>;
  readCombinedData: () => Promise<any>;
}

interface DocumentMetadata {
  id: string;
  fileName: string;
  fileSize: number;
  uploadTimestamp: number;
  category: string;
  mimeType: string;
  extension: string;
  thumbnailPath?: string;
  contextId?: string;
  contextLabel?: string;
  groupKey?: string;
}

interface DocumentsContext {
  list: () => Promise<DocumentMetadata[]>;
  acceptedTypes: () => Promise<string[]>;
  upload: (
    filePaths: string[],
    category: string,
    context?: { contextId?: string; contextLabel?: string; groupKey?: string },
  ) => Promise<{ ok: boolean; document?: DocumentMetadata; error?: string }[]>;
  delete: (id: string) => Promise<{ ok: boolean }>;
  download: (id: string) => Promise<{ ok: boolean; filePath?: string }>;
  open: (id: string) => Promise<{ ok: boolean }>;
  onProgress: (
    handler: (payload: {
      id: string;
      progress: number;
      status: "uploading" | "success" | "error";
      error?: string;
      fileName?: string;
      fileSize?: number;
      extension?: string;
      category?: string;
      contextId?: string;
      contextLabel?: string;
      groupKey?: string;
    }) => void,
  ) => () => void;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  planning: PlanningContext;
  documents: DocumentsContext;
  payroll: {
    acceptedInputs: () => Promise<string[]>;
    run: (
      scriptKey: string,
      args: { inputFiles: string[]; options?: Record<string, unknown> },
    ) => Promise<{ ok: boolean; runId?: string; error?: string }>;
    listResults: () => Promise<
      Array<{ id: string; label: string; createdAt: number; filePath: string; size: number; mimeType?: string }>
    >;
    downloadResult: (id: string) => Promise<{ ok: boolean; filePath?: string; error?: string }>;
    onProgress: (
      handler: (payload: { runId: string; progress: number; status: "running" | "success" | "error"; message?: string; error?: string }) => void,
    ) => () => void;
  };
}
